### ISSUE TITLE
Playlists capped at 50 

### ISSUE THREAD

**Issue by octoshrimpy** [ceuk/spotui#21]
**Is your feature request related to a problem? Please describe.**
Only around 52 playlists are visible, out of the 80+ 

**Describe the solution you'd like**
Either list all playlists in a flattened directory, or integrate with [spotify-folder](https://github.com/mikez/spotify-folders) to provide a better view. 

**Describe alternatives you've considered**
I've migrated to spotui from spotify-tui (even though I prefer the arrow nav from *-tui) simply because this is python and I don't know rust :sweat_smile: this way I can help contribute. 

**Additional context**
for smaller screens, scrolling name of playlists, songs & artists would be very beneficial as well, since there are a lot of songs with naming schemas such as `mihoy remix - Renegade: <song name>` and in smaller screens the user simply gets `mihoy remix - Renega...`

---

I'd also like to help where I can towards theming, as this is what mine looks like at the moment: 
![image](https://user-images.githubusercontent.com/7097172/120027942-430d6500-bfb1-11eb-8438-9a237296e663.png)

**Comment by octoshrimpy** [comment]
I'm also up for helping convert from barebones curses to [blessings](https://pypi.org/project/blessings/)

**Comment by ceuk** [comment]
Hey,

The playlist issue is due to there being a limit of 50 items on the playlist endpoint and I don't bother fetching the additional ones after the first request. Should be a simple fix (I'll track that using this issue).

On the other stuff you mentioned: User themes would be a nice feature and would be pretty trivial to implement. Autoscrolling truncated text is a cool idea too. Not too sure about rewriting the UI as curses isn't causing any issues currently to my knowledge. 

If you do fancy contributing I'll create issues for the above 2 with a brief guide on implementation. Feel free to raise a PR for one/both of them - (and thanks :slightly_smiling_face: ) 

Edit: see #22 and #23  :)

**Comment by diegoulloao** [comment]
Is this resolved?

**Comment by octoshrimpy** [comment]
no, not yet. I'm thinking if the API doesn't tell us how many songs there are total, the just query the api for the next "page" until the results are less than 50.
I'm currently busy with another project, so I can't crank time into this quite yet.

**Comment by octoshrimpy** [comment]
@diegoulloao took a couple hours today and cranked it out for you. will be coming soon, available at https://github.com/octoshrimpy/spotui/commit/6684f4b66c46ff4bd695935aacf26c486daa814e

**Comment by diegoulloao** [comment]
Great man!!! you're the best, I use spotui every day at work. Thank you man, waiting for the release :)

**Comment by ceuk** [comment]
@octoshrimpy Just in case you miss the comment on your PR: 

I've split out the playlist stuff into a separate PR (#27) as this might take a while to get merged and I know @diegoulloao is waiting for the fix :) This way we can deal with that one separately - looks fine subject to a quick test (see [my comment](https://github.com/ceuk/spotui/pull/27/files/3049180885ec69bbb62988c6a5b20488e328f1c1#diff-f99f2b584c1c0fb752b5d4a16b009f481aed74737285d7bc26808da326b5ae84))

I've also split up the rest of the commits into two sections:

#29 General improvements
#28 Theme support (and config improvements)

I've invited you as a collaborator to the repo so you should be able to make changes to these new PRs

**Comment by octoshrimpy** [comment]
sounds good! 
I'll go through those PRs and clean up any unnecessary code that I may have left (PR was submitted rather late at night haha). For now, test #27 for first merge, and then #28 next?

**Comment by ceuk** [comment]
~Sigh, I've just realised you can't see any of my change request comments because I'm now the author of the PR and authors can't request changes on their own PRs~ 🤦 

~Would you be able to re-create all 3 PRs? I'll close the current ones, that way I can be assigned as the reviewer. What a nightmare~

Edit: nevermind, sorted - you should be able to see them now
